apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-default
  namespace: {{ .Values.namespace }}
data:
  proxy-default.conf: |
{{ .Values.proxyconfig | indent 4 }}
  compression.conf: |
{{ .Values.compressionConfig | indent 4 }}
